###
# Get all classrooms
GET http://localhost:3333/classrooms HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJoaWV1QDEyMy5jb20iLCJmaXJzdF9uYW1lIjpudWxsLCJsYXN0X25hbWUiOm51bGwsImJpbyI6bnVsbCwiaWF0IjoxNjUxNjc3MzM5LCJleHAiOjE2NTE2ODQ1Mzl9.kdanxB6MeC9_yugYmM3_EXT7_JPnRgZIEuFenZmqA3I

###
# Get one classrooms
GET http://localhost:3333/classrooms/2 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJoaWV1QDEyMy5jb20iLCJmaXJzdF9uYW1lIjpudWxsLCJsYXN0X25hbWUiOm51bGwsImJpbyI6bnVsbCwiaWF0IjoxNjUxNjc3MzM5LCJleHAiOjE2NTE2ODQ1Mzl9.kdanxB6MeC9_yugYmM3_EXT7_JPnRgZIEuFenZmqA3I


###
# Create new classroom
POST http://localhost:3333/classrooms HTTP/1.1
content-type: application/json

  {
    "name": "Huynh's Class",
    "created_by": 1
  }

  /classrooms/:id/invite

###
# invite to classroom
POST http://localhost:3333/classrooms/1/invite HTTP/1.1
content-type: application/json

  {
    "user_id": 2
  }

###
# invite to classroom
POST http://localhost:3333/classrooms/1/event HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJodXluaHRydW5naGlldTIwMDBAZ21haWwuY29tIiwiZmlyc3RfbmFtZSI6IkhpZXUiLCJsYXN0X25hbWUiOiJIdXluaCIsImJpbyI6IkZFIERldiIsImlzX2FkbWluIjpmYWxzZSwiaWF0IjoxNjU2MTcxMTQ0LCJleHAiOjE2NTY3NzU5NDR9.yHICiZxZvc-FQ9_m2JsCGkmUa-UHjDglgJjBgJ4c8wo

  {
    "id": 5,
    "event": {
      "name": "alo?"
    }
  }